name: Deploy React App

on:
  pull_request:
    branches:
      - master
      
permissions:
      contents: write  # Allow write access to contents (push to repository)

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: typescript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd ProductListFetch
          npm install

      - name: Build React App
        run: |
          cd ProductListFetch
          npm run build

  deploy:
    needs: build  # The deploy job runs after the build job finishes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Example GitHub Pages)
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
