name: Deploy React App

on:
  pull_request:
    branches:
      - master
      
permissions:
      contents: write  # Allow write access to contents (push to repository)

jobs:
  codeql:
    runs-on : ubuntu-latest
    name: "Scanning with CodeQL"
    steps:
      - name: CheckOut Code
        uses: actions/checkout@v3

      - name: Set up CodeQL
        uses: github/codeql-action/setup-codeql@v2
      
      - name: Initialize CodeQL database
        run: |
          mkdir -p ${{ github.workspace }}/codeql-db
          codeql database create ${{ github.workspace }}/codeql-db --language=typescript --source-root=${{ github.workspace }}
      
      - name: Perform CodeQL analysis
        run: |
          codeql database analyze ${{ github.workspace }}/codeql-db --format=sarif-latest --output=codeql-results.sarif  

      - name: Upload CodeQL results
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: codeql-results.sarif

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd ProductListFetch
          npm install

      - name: Build React App
        run: |
          cd ProductListFetch
          npm run build

  deploy:
    needs: build  # The deploy job runs after the build job finishes successfully
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Example GitHub Pages)
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
